// Code generated by protoc-gen-go. DO NOT EDIT.
// source: capture.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	capture.proto

It has these top-level messages:
	VideoCaptureRequest
	OverlayImage
	VideoCaptureReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VideoCaptureRequest struct {
	Video  []byte `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Width  int32  `protobuf:"varint,3,opt,name=width" json:"width,omitempty"`
	Height int32  `protobuf:"varint,4,opt,name=height" json:"height,omitempty"`
	Time   int64  `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
}

func (m *VideoCaptureRequest) Reset()                    { *m = VideoCaptureRequest{} }
func (m *VideoCaptureRequest) String() string            { return proto.CompactTextString(m) }
func (*VideoCaptureRequest) ProtoMessage()               {}
func (*VideoCaptureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VideoCaptureRequest) GetVideo() []byte {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *VideoCaptureRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VideoCaptureRequest) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *VideoCaptureRequest) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VideoCaptureRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type OverlayImage struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	X    int32  `protobuf:"varint,2,opt,name=x" json:"x,omitempty"`
	Y    int32  `protobuf:"varint,3,opt,name=y" json:"y,omitempty"`
}

func (m *OverlayImage) Reset()                    { *m = OverlayImage{} }
func (m *OverlayImage) String() string            { return proto.CompactTextString(m) }
func (*OverlayImage) ProtoMessage()               {}
func (*OverlayImage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OverlayImage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *OverlayImage) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *OverlayImage) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type VideoCaptureReply struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *VideoCaptureReply) Reset()                    { *m = VideoCaptureReply{} }
func (m *VideoCaptureReply) String() string            { return proto.CompactTextString(m) }
func (*VideoCaptureReply) ProtoMessage()               {}
func (*VideoCaptureReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VideoCaptureReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*VideoCaptureRequest)(nil), "pb.VideoCaptureRequest")
	proto.RegisterType((*OverlayImage)(nil), "pb.OverlayImage")
	proto.RegisterType((*VideoCaptureReply)(nil), "pb.VideoCaptureReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VideoCapture service

type VideoCaptureClient interface {
	ExtractImage(ctx context.Context, opts ...grpc.CallOption) (VideoCapture_ExtractImageClient, error)
}

type videoCaptureClient struct {
	cc *grpc.ClientConn
}

func NewVideoCaptureClient(cc *grpc.ClientConn) VideoCaptureClient {
	return &videoCaptureClient{cc}
}

func (c *videoCaptureClient) ExtractImage(ctx context.Context, opts ...grpc.CallOption) (VideoCapture_ExtractImageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VideoCapture_serviceDesc.Streams[0], c.cc, "/pb.VideoCapture/ExtractImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &videoCaptureExtractImageClient{stream}
	return x, nil
}

type VideoCapture_ExtractImageClient interface {
	Send(*VideoCaptureRequest) error
	CloseAndRecv() (*VideoCaptureReply, error)
	grpc.ClientStream
}

type videoCaptureExtractImageClient struct {
	grpc.ClientStream
}

func (x *videoCaptureExtractImageClient) Send(m *VideoCaptureRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *videoCaptureExtractImageClient) CloseAndRecv() (*VideoCaptureReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(VideoCaptureReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for VideoCapture service

type VideoCaptureServer interface {
	ExtractImage(VideoCapture_ExtractImageServer) error
}

func RegisterVideoCaptureServer(s *grpc.Server, srv VideoCaptureServer) {
	s.RegisterService(&_VideoCapture_serviceDesc, srv)
}

func _VideoCapture_ExtractImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoCaptureServer).ExtractImage(&videoCaptureExtractImageServer{stream})
}

type VideoCapture_ExtractImageServer interface {
	SendAndClose(*VideoCaptureReply) error
	Recv() (*VideoCaptureRequest, error)
	grpc.ServerStream
}

type videoCaptureExtractImageServer struct {
	grpc.ServerStream
}

func (x *videoCaptureExtractImageServer) SendAndClose(m *VideoCaptureReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *videoCaptureExtractImageServer) Recv() (*VideoCaptureRequest, error) {
	m := new(VideoCaptureRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _VideoCapture_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VideoCapture",
	HandlerType: (*VideoCaptureServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExtractImage",
			Handler:       _VideoCapture_ExtractImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "capture.proto",
}

func init() { proto.RegisterFile("capture.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xb9, 0xb6, 0xa9, 0xd4, 0x93, 0x19, 0x30, 0xff, 0x2c, 0xa6, 0x28, 0x0b, 0x9e, 0x32,
	0xc0, 0xce, 0x00, 0x62, 0x60, 0x42, 0xf2, 0xc0, 0xee, 0x34, 0xa7, 0x26, 0x52, 0x42, 0x4c, 0xb8,
	0x96, 0x78, 0xe4, 0x9b, 0x23, 0xdb, 0x19, 0x40, 0x74, 0x7b, 0xef, 0xee, 0xe9, 0x7e, 0xf6, 0xc3,
	0xd3, 0xad, 0x75, 0xbc, 0x1f, 0xa9, 0x74, 0xe3, 0xc0, 0x83, 0x5c, 0xb8, 0xaa, 0xf8, 0x06, 0x3c,
	0x7f, 0x6b, 0x6b, 0x1a, 0x9e, 0xd2, 0xca, 0xd0, 0xc7, 0x9e, 0x3e, 0x59, 0x5e, 0x60, 0x76, 0x08,
	0x63, 0x05, 0x39, 0x68, 0x61, 0x92, 0x91, 0x12, 0x57, 0xef, 0xb6, 0x27, 0xb5, 0xc8, 0x41, 0x6f,
	0x4c, 0xd4, 0x21, 0xf9, 0xd5, 0xd6, 0xdc, 0xa8, 0x65, 0x0e, 0x3a, 0x33, 0xc9, 0xc8, 0x2b, 0x5c,
	0x37, 0xd4, 0xee, 0x1a, 0x56, 0xab, 0x38, 0x9e, 0x5d, 0xb8, 0xc0, 0x6d, 0x4f, 0x2a, 0xcb, 0x41,
	0x2f, 0x4d, 0xd4, 0xc5, 0x03, 0x8a, 0xd7, 0x03, 0x8d, 0x9d, 0xf5, 0x2f, 0xbd, 0xdd, 0x51, 0xc8,
	0x38, 0xcb, 0x4d, 0x44, 0x6f, 0x4c, 0xd4, 0x52, 0x20, 0x4c, 0x11, 0x9b, 0x19, 0x98, 0x82, 0xf3,
	0x33, 0x0f, 0x7c, 0x71, 0x8b, 0x67, 0x7f, 0xbf, 0xe0, 0x3a, 0x1f, 0x8e, 0xd4, 0x96, 0xed, 0xfc,
	0xfe, 0xa8, 0xef, 0x0c, 0x8a, 0xdf, 0x41, 0xf9, 0x88, 0xe2, 0x79, 0xe2, 0xd1, 0x6e, 0x39, 0x81,
	0xaf, 0x4b, 0x57, 0x95, 0x47, 0xda, 0xb8, 0xb9, 0xfc, 0xbf, 0x70, 0x9d, 0x2f, 0x4e, 0x34, 0x54,
	0xeb, 0xd8, 0xe5, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0xe1, 0x82, 0x7c, 0x5c, 0x01,
	0x00, 0x00,
}
